### ISSUE TITLE
Would this work with a HTML website?

### ISSUE THREAD

**Issue by GiacomoLaw** [keesL/metar#2]
Looking for a source for metars: https://github.com/GiacomoLaw/QuickMETAR

I'd like the user to search for an ICAO code, and then the METAR to be returned. Would this work for it?

Thanks!

**Comment by keesL** [comment]
Yes, it would:

```
$ metar kjfk
KJFK 141151Z 02011KT 10SM FEW032 10/02 A3032 RMK AO2 SLP267 70001 T01000022 10117 20083 52023
```
Is that what you are looking for?

**Comment by GiacomoLaw** [comment]
Is there any way I can get the user to search for a metar, and this turns it up?

**Comment by keesL** [comment]
Sure; build a web form, capture its input, fork out a metar process and feed its output back to the web server. That should be pretty easy to build.

**Comment by GiacomoLaw** [comment]
Okay, thank you very much! Where should I put the credits, and what should I link to?

**Comment by GiacomoLaw** [comment]
Thanks for the help!
